/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MaplibreMap {
        /**
          * If true, the map's position (zoom, center latitude, center longitude, bearing, and pitch) will be synced with the hash fragment of the page's URL. <br/> An additional string may optionally be provided to indicate a parameter-styled hash, *e.g. http://path/to/my/page.html#map=2.59/39.26/53.07/-24.1/60&foo=bar* , where foo is a custom parameter and bar is an arbitrary hash distinct from the map hash.
         */
        "hash": boolean | string;
        /**
          * The maximum pitch of the map (0-85). Values greater than 60 degrees are experimental and may result in rendering issues.
         */
        "maxPitch": number;
        /**
          * The maximum zoom level of the map (0-24)
         */
        "maxZoom": number;
        /**
          * The minimum pitch of the map (0-85). Values greater than 60 degrees are experimental and may result in rendering issues.
         */
        "minPitch": number;
        /**
          * The minimum zoom level of the map (0-24)
         */
        "minZoom": number;
    }
}
declare global {
    interface HTMLMaplibreMapElement extends Components.MaplibreMap, HTMLStencilElement {
    }
    var HTMLMaplibreMapElement: {
        prototype: HTMLMaplibreMapElement;
        new (): HTMLMaplibreMapElement;
    };
    interface HTMLElementTagNameMap {
        "maplibre-map": HTMLMaplibreMapElement;
    }
}
declare namespace LocalJSX {
    interface MaplibreMap {
        /**
          * If true, the map's position (zoom, center latitude, center longitude, bearing, and pitch) will be synced with the hash fragment of the page's URL. <br/> An additional string may optionally be provided to indicate a parameter-styled hash, *e.g. http://path/to/my/page.html#map=2.59/39.26/53.07/-24.1/60&foo=bar* , where foo is a custom parameter and bar is an arbitrary hash distinct from the map hash.
         */
        "hash"?: boolean | string;
        /**
          * The maximum pitch of the map (0-85). Values greater than 60 degrees are experimental and may result in rendering issues.
         */
        "maxPitch"?: number;
        /**
          * The maximum zoom level of the map (0-24)
         */
        "maxZoom"?: number;
        /**
          * The minimum pitch of the map (0-85). Values greater than 60 degrees are experimental and may result in rendering issues.
         */
        "minPitch"?: number;
        /**
          * The minimum zoom level of the map (0-24)
         */
        "minZoom"?: number;
    }
    interface IntrinsicElements {
        "maplibre-map": MaplibreMap;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "maplibre-map": LocalJSX.MaplibreMap & JSXBase.HTMLAttributes<HTMLMaplibreMapElement>;
        }
    }
}
