/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { LngLatLike } from "maplibre-gl";
export namespace Components {
    interface MaplibreBase {
    }
    interface MaplibreMarker {
        /**
          * The latitude & longitude of the marker. Should be an 2-length number array or a JSON Array string (E.g. [0.2354, 10.554])
         */
        "lngLat": LngLatLike | string;
    }
}
declare global {
    interface HTMLMaplibreBaseElement extends Components.MaplibreBase, HTMLStencilElement {
    }
    var HTMLMaplibreBaseElement: {
        prototype: HTMLMaplibreBaseElement;
        new (): HTMLMaplibreBaseElement;
    };
    interface HTMLMaplibreMarkerElement extends Components.MaplibreMarker, HTMLStencilElement {
    }
    var HTMLMaplibreMarkerElement: {
        prototype: HTMLMaplibreMarkerElement;
        new (): HTMLMaplibreMarkerElement;
    };
    interface HTMLElementTagNameMap {
        "maplibre-base": HTMLMaplibreBaseElement;
        "maplibre-marker": HTMLMaplibreMarkerElement;
    }
}
declare namespace LocalJSX {
    interface MaplibreBase {
    }
    interface MaplibreMarker {
        /**
          * The latitude & longitude of the marker. Should be an 2-length number array or a JSON Array string (E.g. [0.2354, 10.554])
         */
        "lngLat": LngLatLike | string;
    }
    interface IntrinsicElements {
        "maplibre-base": MaplibreBase;
        "maplibre-marker": MaplibreMarker;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "maplibre-base": LocalJSX.MaplibreBase & JSXBase.HTMLAttributes<HTMLMaplibreBaseElement>;
            "maplibre-marker": LocalJSX.MaplibreMarker & JSXBase.HTMLAttributes<HTMLMaplibreMarkerElement>;
        }
    }
}
